GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons

###
http://localhost:3001/api/persons/1

###
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Holaa",
  "number": "040-123456"
}

###
DELETE http://localhost:3001/api/persons/686966848